lanews/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lanews.Data;
using lanews.Models;
using Microsoft.AspNetCore.Authorization;
using lanews.Services;
using Microsoft.AspNetCore.Identity;

namespace lanews.Controllers
{
    [Authorize(Roles = "Administrator, Editor")]
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IArticleService _articleService;
        private readonly UserManager<User> _userManager;

        public ArticlesController(ApplicationDbContext context, IArticleService articleService, UserManager<User> userManager)
        {
            _context = context;
            _articleService = articleService;
            _userManager = userManager;
        }
          
        // GET: All Articles
        public IActionResult Index()
        {
            IEnumerable<Article> publishedArticles = _articleService.GetArticlesByStatus("published");
            return View(publishedArticles);
        }

        //GET: Articles by user
        [Authorize(Roles = "Editor")]
        public IActionResult MyArticles()
        {
            var articles = _articleService.GetArticlesByAuthorId(_userManager.GetUserId(User));
            return View(articles);
        }

        // GET: Articles/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(a => a.Autor)
                .Include(a => a.Category)
                .Include(a => a.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName");
            ViewData["StatusId"] = new SelectList(_context.ArticleStatuses, "Id", "StatusName");
            return View();
        }

        // POST: Articles/Create    
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StatusId,CreationDate,ModificationDate,HeadLine,SubHeading,Lead,Body,CategoryId,AutorId,ReadCount,FeaturedImageUrl,FeaturedImageCaption,FeaturedImageAlt,WhereLine")] Article article)
        {
            if (ModelState.IsValid)
            {
                await _articleService.CreateArticle(article);
               return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", article.Category.CategoryName);
            ViewData["StatusId"] = new SelectList(_context.ArticleStatuses, "Id", "Id", article.Status.StatusName);
            return View(article);
        }

        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.Include(a => a.Autor).FirstOrDefaultAsync(a => a.Id == id);
            if (article == null)
            {
                return NotFound();
            }
            if(User.Identity.Name != article.Autor.UserName)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorId"] = new SelectList(_context.Users, "Id", "FisrtName", article.AutorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", article.CategoryId);
            ViewData["StatusId"] = new SelectList(_context.ArticleStatuses, "Id", "Id", article.StatusId);
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,StatusId,CreationDate,ModificationDate,HeadLine,SubHeading,Lead,Body,CategoryId,AutorId,ReadCount,FeaturedImageUrl,FeaturedImageCaption,FeaturedImageAlt,WhereLine")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (User.Identity.Name != article.Autor.UserName)
                {
                    return RedirectToAction(nameof(Index));
                }
                try
                {
                    article.ModificationDate = DateTime.Now;
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutorId"] = new SelectList(_context.Users, "Id", "FisrtName", article.AutorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", article.CategoryId);
            ViewData["StatusId"] = new SelectList(_context.ArticleStatuses, "Id", "Id", article.StatusId);
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(a => a.Autor)
                .Include(a => a.Category)
                .Include(a => a.Status)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }
            if (User.Identity.Name != article.Autor.UserName)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            
            var article = await _context.Articles.FindAsync(id);
            if (User.Identity.Name != article.Autor.UserName)
            {
                return RedirectToAction(nameof(Index));
            }
            _context.Articles.Remove(article);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Articles/Caregories/sport
        [AllowAnonymous]
        public async Task<IActionResult> Categories(string id)
        {
            bool categoryExists = _context.Categories.Where(c => c.CategoryName == id).Count() == 0  ? false: true;
           
            if (categoryExists)
            {
                var articles = await _context.Articles
               .Include(a => a.Category)
               .Where(a => a.Category
               .CategoryName == id)
               .ToListAsync();

                ViewBag.category = id;

                return View(articles);
            }
            else
            {
                return NotFound();
            }
        }
        private bool ArticleExists(Guid id)
        {
            return _context.Articles.Any(e => e.Id == id);
        }
        
    }
}

lanews/Views/Shared/_AdminOptions.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager



@if (User.IsInRole("Administrator"))
{
    <li class="nav-item"><a class="dropdown-item" href="#"><i class="fa fa-landmark"></i>Dashboard</a></li>
}

lanews/Views/Shared/_BreakingNews.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<section class="container breaking-news centered-content">
    <div class="red-strap">
        <h2>// Breaking news //</h2>
    </div>
    <div class="text-wrapper">
        <p>Loremst, amet consectetur adipisicing elit. Loremst, amet consectetur adipisicing elit. Loremst, amet consectetur adipisicing elit. Loremst, amet consectetur adipisicing elit.</p>
    </div>
</section>

lanews/Views/Shared/_EditorOptions.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager



@if (User.IsInRole("Editor"))
{
    <li class="nav-item"><a class="dropdown-item"  asp-controller="Articles" asp-action="MyArticles" ><i class="fa fa-list-alt"></i>My articles</a></li>
    <li class="nav-item"><a class="dropdown-item" asp-controller="Articles" asp-action="Create"><i class="fa fa-edit"></i>Write</a></li>
}

lanews/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<footer>
    <div class="content-wrapper container centered-content">
        <section class="the-company">
            <h3 class="footer=logo">LA NEWS</h3>
            <p>
                Lorem ipsum dolor sit Et sed nam corrupti ipsam earum corrupti ipsam
                earum.
            </p>
        </section>
        <section class="news-sections">
            <h3 class="section-title">About us</h3>
            <ul class="news-section-list">
                <li>
                    <a asp-controller="Home" asp-action="About" class="news-section-link">History</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="About" class="news-section-link">Mission, vision and values</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="About" class="news-section-link">Our team</a>
                </li>
            </ul>
        </section>
        <section class="news-sections">
            <h3 class="section-title">News sections</h3>
            <ul class="news-section-list">
                <li>
                    <a href="#" class="news-section-link">Politics</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Business</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Health</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Entertainment</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Sports</a>
                </li>
            </ul>
        </section>
        <section class="news-sections">
            <h3 class="section-title">Follow us</h3>
            <ul class="news-section-list">
                <li>
                    <a href="#" class="news-section-link">Facebook</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Twitter</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Instagram</a>
                </li>
                <li>
                    <a href="#" class="news-section-link">Youtube</a>
                </li>
            </ul>
        </section>
        <div class="copy">
            <p>
                Copyright © 2020 LA NEWS LLC <br />
                All rights reserved.
            </p>
        </div>
        <a class="go-to-top" href="#top"><span>^</span></a>
    </div>
</footer>

lanews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Politics, Business, Entertainment, Sports, news, la news" />
    <meta name="description"
          content="Most vibrant newspaper in L.A. Find the latest news about politics, business, entertaintment, sports and more" />
    <meta property="og:image" content="" />
    <meta property="og:description"
          content="Most vibrant newspaper in L.A. Find the latest news about politics, business, entertaintment, sports and more" />
    <meta property="og:title" content="L.A. News" />
    <meta name="author" content="Josue F. Contreras" />
    <link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png" />
    <title>@ViewData["Title"] - LA NEWS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    </environment>
    @await RenderSectionAsync("CustomStyle", required: false)
</head>
<body>
    <a id="top"></a>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LA News</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".main-nav" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between main-navbar">
                    <ul class="navbar-nav flex-grow-1 page-list">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        <partial name="_categoryNav" />
    </header>
    <partial name="_homeHero" />
    <section class="container">
        <main role="main" class="py-3">
            @RenderBody()
        </main>
    </section>
    <partial name="_Footer"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

lanews/Views/Shared/_categoryNav.cshtml
@inject ApplicationDbContext _context

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark cat-navbar justify-content-end">
    <div class="container justify-content-center">
        <button class="navbar-toggler p-0" type="button" data-toggle="collapse" data-target=".cat-list" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between cat-list">
            <ul class="navbar-nav flex-grow-1">
                @foreach (var category in _context.Categories.ToList())
                {
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Categories" asp-route-id="@category.CategoryName">@category.CategoryName</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

lanews/Views/Shared/_homeHero.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var controller = ViewContext.RouteData.Values["controller"];
    var action = ViewContext.RouteData.Values["action"]; ;
}

@if (controller != null && action !=null && controller.ToString() == "Home" && action.ToString() == "Index")
{
    <section class="hero">
        <div class="hero-content">
            <h1 class="title">
                Most <span class="vibrant">Vibrant</span> Newspaper in L.A.
            </h1>
            <h2>Politics | Business | Health | Entertainment | Sports</h2>
        </div>
    </section>
}